services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spendle
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always
    tty: true

  db:
    image: mysql:8
    container_name: spendle_db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spendle_dev
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
