version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spendle
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql2://root:password@db:3306/spended_dev

  db:
    image: mysql:8
    container_name: spendle_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spendle_dev
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
